title: "DeepSeek-OCR: Contexts Optical Compression"
arxiv_id: "2510.18234"
arxiv_url: "https://arxiv.org/abs/2510.18234v1"
doi: "10.48550/arXiv.2510.18234"
categories: ["cs.CV"]
date: "2025-10-22"
status: "in-progress"
tags: ["OCR", "Document Understanding", "Vision", "DeepSeek"]
authors:
  - "Haoran Wei"
  - "Yaofeng Sun"
  - "Yukun Li"
source_pdf: "paper/DeepSeek-OCR.pdf"
