name: Monthly Assessment Reminder

on:
  schedule:
    - cron: '0 8 1 * *'
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create monthly reminder issue if not exists
        uses: actions/github-script@v7
        with:
          script: |
            const now = new Date();
            const yyyy = now.getUTCFullYear();
            const mm = String(now.getUTCMonth()+1).padStart(2,'0');
            const tag = `${yyyy}-${mm}`;
            const title = `Assessment: ${tag}`;
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'assessment',
              state: 'open',
              per_page: 100
            });
            if (issues.find(i => i.title.includes(tag))) {
              core.info(`Issue for ${tag} already exists.`);
              return;
            }
            const body = [
              `Напоминание на ${tag}. Пройдите тест в веб-интерфейсе (24 вопроса):`,
              ``,
              `➡️ https://${context.repo.owner}.github.io/${context.repo.repo}/web/assessment.html?m=${tag}`,
              ``,
              `После завершения вставьте JSON в этот issue (в код-блоке) или приложите файл ${tag}.json.`,
              `Закрытие issue автоматически запустит сборку Radar (или дождитесь ночного запуска).`
            ].join('\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              labels: ['assessment'],
              body
            });

